{% set name = "appscript" %}
{% set version = "1.2.4" %}
{% set sha256 = "c8f28ee2802a5f61f097361045887af8ea7442ef17b256b4ab3d3fad11b23c15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-Drop-bad-valued-MAC_OS_X_VERSION_MIN_REQUIRED.patch

build:
  number: 0
  skip: true  # [not osx]
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools

  run:
    - python
    - lxml >=4.7.1

test:
  imports:
    - aem
    - appscript
    - mactypes
    - osax
    - aem.ae

about:
  home: http://appscript.sourceforge.net
  license: Public Domain
  summary: Control AppleScriptable applications from Python.
  description: |
    Appscript is a user-friendly Apple event bridge that allows users to
    control scriptable Mac OS X applications from Python, Ruby and Objective-C.
    Appscript makes these languages serious alternatives to Apple's own
    AppleScript language for automating your Mac.
  dev_url: http://svn.code.sf.net/p/appscript/code/py-appscript/
  doc_url: https://pypi.python.org/pypi/appscript
  doc_source_url: http://appscript.sourceforge.net/py-appscript/index.html

extra:
  recipe-maintainers:
    - nehaljwani
